### ISSUE TITLE
Add CI/CD pipelines

### ISSUE THREAD

**Issue by DSergiu** [hCaptcha/vue-hcaptcha#25]
**Goal**: add CI/CD pipelines

**Why**: Streamline integration and packaging

**Implementation plan**:

- [x] Add CI pipeline which:
  - [x] ` installs frozen packages` 
  - [x] `lints code`
  - [x] `runs test`
  - [x] `checks version bump against master`

- [x] Add CD pipeline which:
  - [x] ` installs frozen packages` 
  - [x] `lints code`
  - [x] `runs test`
  - [x] `deploys package to npm upon new release`

Example ci runs:
* PASS https://github.com/hCaptcha/vue-hcaptcha/runs/1594998213
* FAIL https://github.com/hCaptcha/vue-hcaptcha/actions/runs/438105418
